### ISSUE TITLE
Add build.env and remove builder version

### ISSUE THREAD

**Issue by lispking** [amphitheatre-app/amp-example-aleo#3]
Update .amp.toml

```toml
[build]
builder = "ghcr.io/amp-buildpacks/leo-builder"

[partners]
snarkos = { version = "latest", registry = "catalog" }

[build.env]
BP_ALEO_DEPLOY_PRIVATE_KEY = "APrivateKeyxxx"
```
